version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - APP_PORT=3000 

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"